server:
  port: 9000


eureka:
  client:
    enabled: false

spring:
  application:
    name: auth-service
  datasource:
    url:  jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


token:
  secret: vsdab1232fkewbquriebp12315555555aa
  expiration: 60000