server:
  port: 9000

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/music_test2?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: kjm

token:
  secret: vsdab1232fkewbquriebp12315555555aa
  expiration: 600000